// Generated by CoffeeScript 2.7.0
var insertTimestamp;

console.log('Hello from the background script!');

insertTimestamp = function() {
  var inputField, timestamp;
  inputField = document.querySelector("prompt-textarea");
  if (inputField) {
    timestamp = new Date().toISOString();
    return inputField.value = `[${timestamp}] ` + inputField.value;
  }
};

document.addEventListener("DOMContentLoaded", insertTimestamp);

browser.webRequest.onCompleted.addListener(function(details) {
  console.log("Response received at:", new Date().toISOString());
  return insertTimestamp();
}, {
  urls: ["*://chat.openai.com/*"] // Adjust if needed
});
