// Generated by CoffeeScript 2.7.0
document.addEventListener('DOMContentLoaded', function() {
  document.getElementById('greet').addEventListener('click', function() {
    alert('Hello, World!');
  });
});
